#!/usr/bin/env bash
# membench.sh — measure how much host RAM boxman VMs actually hold onto
# after a guest allocates and frees memory (virtio-balloon free-page-reporting
# A/B test helper).
#
# Run on the libvirt host. The script:
#   t0: record QEMU RSS per VM + host memory
#      churn: each VM allocates+dirty-frees CHURN_MB inside the guest
#   t1: record again (expect baseline + churn)
#      sleep SETTLE seconds (free-page reporting is asynchronous)
#   t2: record again (with free_page_reporting=on this drops back near t0)
#
# Usage:
#   membench.sh -p <project> -c <cluster> -F <workspace ssh_config> [options] vm...
#
# Options:
#   -p PROJECT     boxman project name (used to derive libvirt domain names:
#                  bprj__<project>__bprj_<cluster>_<vm>)
#   -c CLUSTER     cluster name (default: cluster_1)
#   -F SSH_CONFIG  workspace ssh_config generated by boxman (for the churn step)
#   -m CHURN_MB    MiB to allocate+free per guest (default: 700)
#   -s SETTLE      seconds to wait between t1 and t2 (default: 90)
#   -u SSH_USER    guest user for the churn ssh (default: admin)
#   --no-churn     skip the churn step (measure only)
#
# Environment:
#   VIRSH_CMD      virsh invocation to use (default: "virsh"; use
#                  "sudo virsh" when the system URI needs root)
#   SSHPASS        guest password; when set, churn uses sshpass with
#                  password auth instead of BatchMode pubkey auth
#   BY_IP=1        resolve each VM's IP via `virsh domifaddr --source agent`
#                  and ssh to it directly, instead of using the workspace
#                  ssh_config (useful when that config is stale)
#
# Example (from the box project dir on the hypervisor):
#   scripts/membench.sh -p membench -c cluster_1 \
#       -F ~/workspaces/membench/ssh_config node01 node02 node03

set -euo pipefail

PROJECT=""
CLUSTER="cluster_1"
SSH_CONFIG=""
CHURN_MB=700
SETTLE=90
SSH_USER=admin
DO_CHURN=1
VIRSH_CMD="${VIRSH_CMD:-virsh}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        -p) PROJECT="$2"; shift 2 ;;
        -c) CLUSTER="$2"; shift 2 ;;
        -F) SSH_CONFIG="$2"; shift 2 ;;
        -m) CHURN_MB="$2"; shift 2 ;;
        -s) SETTLE="$2"; shift 2 ;;
        -u) SSH_USER="$2"; shift 2 ;;
        --no-churn) DO_CHURN=0; shift ;;
        -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
        *) break ;;
    esac
done

VMS=("$@")
if [[ ${#VMS[@]} -eq 0 ]]; then
    echo "error: no VMs given" >&2
    exit 1
fi
if [[ $DO_CHURN -eq 1 && -z $SSH_CONFIG && ${BY_IP:-0} -ne 1 ]]; then
    echo "error: -F <ssh_config> is required for the churn step (or set BY_IP=1)" >&2
    exit 1
fi

domain_name() {
    local vm="$1"
    if [[ -n $PROJECT ]]; then
        echo "bprj__${PROJECT}__bprj_${CLUSTER}_${vm}"
    else
        echo "$vm"
    fi
}

vm_rss_mib() {
    # QEMU process RSS in MiB. Prefer virsh dommemstat (host-side counter),
    # fall back to ps on the qemu process.
    local dom="$1" rss
    rss=$($VIRSH_CMD dommemstat "$dom" 2>/dev/null | awk '/^rss / {print int($2/1024)}' || true)
    if [[ -z $rss ]]; then
        rss=$(ps -o rss= -C qemu-system-x86 -C qemu-system-x86_64 -C qemu-kvm \
              --no-headers 2>/dev/null | head -1 | awk '{print int($1/1024)}' || true)
    fi
    echo "${rss:-NaN}"
}

host_mem() {
    awk '/^MemTotal:/ {t=$2} /^MemAvailable:/ {a=$2}
         END {printf "%d", (t-a)/1024}' /proc/meminfo
}

collect() {
    local label="$1"
    echo "--- ${label} (host used: $(host_mem) MiB)" >&2
    for vm in "${VMS[@]}"; do
        printf "%s %s\n" "$vm" "$(vm_rss_mib "$(domain_name "$vm")")"
    done
}

ssh_guest() {
    local vm="$1"; shift
    local -a sshcmd
    if [[ ${BY_IP:-0} -eq 1 ]]; then
        local ip
        ip=$($VIRSH_CMD domifaddr --source agent "$(domain_name "$vm")" 2>/dev/null \
             | awk '/ipv4/ && $4 !~ /^127\./ {sub(/\/.*/, "", $4); print $4; exit}')
        if [[ -z $ip ]]; then
            echo "cannot resolve IP for $vm via guest agent" >&2
            return 1
        fi
        sshcmd=(ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no)
        if [[ -n ${SSHPASS:-} ]]; then
            sshcmd=(sshpass -p "$SSHPASS" "${sshcmd[@]}"
                    -o PreferredAuthentications=password -o PubkeyAuthentication=no)
        else
            sshcmd+=(-o BatchMode=yes)
        fi
        "${sshcmd[@]}" "${SSH_USER}@${ip}" "$@"
        return
    fi
    # boxman workspace ssh_config entries are named <cluster>_<vm>
    sshcmd=(ssh -F "$SSH_CONFIG"
            -o ConnectTimeout=10 -o StrictHostKeyChecking=no)
    if [[ -n ${SSHPASS:-} ]]; then
        sshcmd=(sshpass -p "$SSHPASS" "${sshcmd[@]}"
                -o PreferredAuthentications=password -o PubkeyAuthentication=no)
    else
        sshcmd+=(-o BatchMode=yes)
    fi
    "${sshcmd[@]}" "${SSH_USER}@${CLUSTER}_${vm}" "$@"
}

churn() {
    local vm="$1" attempt
    local log="${MEMBENCH_LOG:-/tmp/membench-churn.log}"
    for attempt in 1 2 3; do
        if ssh_guest "$vm" \
            "python3 -c '
import sys
n = ${CHURN_MB} * 1024 * 1024
b = bytearray(n)
for i in range(0, n, 4096):
    b[i] = 1
print(\"touched ${CHURN_MB} MiB\", file=sys.stderr)
'" >>"$log" 2>&1; then
            return 0
        fi
        echo "churn attempt $attempt failed on $vm (see $log)" >&2
        sleep 5
    done
    return 1
}

wait_ready() {
    # freshly provisioned guests may still be booting; wait until every VM
    # answers ssh before measuring
    local vm
    for vm in "${VMS[@]}"; do
        for _ in $(seq 1 18); do
            if ssh_guest "$vm" true 2>/dev/null; then break; fi
            sleep 10
        done
    done
}

declare -A T0 T1 T2

if [[ $DO_CHURN -eq 1 ]]; then
    echo "== waiting for all VMs to answer ssh"
    wait_ready
fi

echo "== t0: baseline (idle)"
while read -r vm rss; do T0[$vm]=$rss; done < <(collect "t0")

if [[ $DO_CHURN -eq 1 ]]; then
    echo "== churn: ${CHURN_MB} MiB per guest (${VMS[*]})"
    pids=()
    for vm in "${VMS[@]}"; do
        churn "$vm" &
        pids+=($!)
    done
    rc=0
    for p in "${pids[@]}"; do wait "$p" || rc=1; done
    if [[ $rc -ne 0 ]]; then
        echo "warning: churn failed on at least one VM (ssh/auth?)" >&2
    fi
fi

echo "== t1: right after churn"
while read -r vm rss; do T1[$vm]=$rss; done < <(collect "t1")

echo "== settling for ${SETTLE}s (free-page reporting is async)"
sleep "$SETTLE"

echo "== t2: after settle"
while read -r vm rss; do T2[$vm]=$rss; done < <(collect "t2")

echo
printf "%-12s %8s %8s %8s %10s\n" "vm" "t0(MiB)" "t1(MiB)" "t2(MiB)" "reclaimed"
for vm in "${VMS[@]}"; do
    t0=${T0[$vm]:-NaN}; t1=${T1[$vm]:-NaN}; t2=${T2[$vm]:-NaN}
    if [[ $t1 != NaN && $t1 -gt 0 && $t2 != NaN ]]; then
        pct=$(awk -v a="$t1" -v b="$t2" -v z="$t0" \
              'BEGIN {d=a-z; if (d<=0) {print "n/a"} else printf "%.0f%%", 100*(a-b)/d}')
    else
        pct="n/a"
    fi
    printf "%-12s %8s %8s %8s %10s\n" "$vm" "$t0" "$t1" "$t2" "$pct"
done
echo
echo "reclaimed = share of the churn-driven RSS growth that was returned to the"
echo "host by t2. With free_page_reporting=on expect high values; without it, ~0%."
